# Generated by Django 4.0.8 on 2023-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
