# Generated by Django 4.0.8 on 2023-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_last_completed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
