# Generated by Django 4.0.8 on 2023-01-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_last_completed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discord_id',
        ),
    ]
