# Generated by Django 4.0.8 on 2023-01-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EasterEgg',
        ),
    ]
